import 'package:shelflife/models/product.dart';

// idea is to first get our product from SL Api
// we parse the Json response for product subsriptions into our product model
// then using the list of products we can do stuff like search for product and implement some logic
// basic version of the model for now
final List<Product> sampleProducts = [
  Product(
    id: "product:6198",
    fullName: "Amatem Softgel",
    unitPrice: 1143,
    basicUnit: "units",
    presentation: 1,
    category: "Antimalarial",
    quantityOnShelf: 10,
    type: "pay_on_delivery",
    eligibleForPAYS: true,
    eligibleForPOD: true,
  ),
  Product(
    id: "product:6157",
    fullName: "Panadol Extra",
    unitPrice: 1206,
    basicUnit: "units",
    presentation: 1,
    category: "Analgesic",
    quantityOnShelf: 10,
    type: "pay_on_delivery",
    eligibleForPAYS: true,
    eligibleForPOD: true,
  ),
  Product(
    id: "product:6299",
    fullName: "Bunto blood Caps",
    unitPrice: 417,
    basicUnit: "units",
    presentation: 1,
    category: "Supplement",
    quantityOnShelf: 10,
    type: "pay_as_you_sell",
    eligibleForPAYS: true,
    eligibleForPOD: true,
  ),
  Product(
    id: "product:6035",
    fullName: "Ventolin Inhaler",
    unitPrice: 1150,
    basicUnit: "units",
    presentation: 1,
    category: "Antiasthmatic",
    quantityOnShelf: 10,
    type: "pay_as_you_sell",
    eligibleForPAYS: true,
    eligibleForPOD: true,
  ),
  Product(
    id: "product:6023",
    fullName: "Postinor 2",
    unitPrice: 489,
    basicUnit: "units",
    presentation: 1,
    category: "Family Planning",
    quantityOnShelf: 10,
    type: "pay_as_you_sell",
    eligibleForPAYS: true,
    eligibleForPOD: true,
  ),
  Product(
    id: "product:6344",
    fullName: "M&B PCM Syrup",
    unitPrice: 186,
    basicUnit: "units",
    presentation: 1,
    category: "Analgesic",
    quantityOnShelf: 10,
    type: "pay_as_you_sell",
    eligibleForPAYS: true,
    eligibleForPOD: true,
  ),
  Product(
    id: "product:6080",
    fullName: "Fleming 625mg",
    unitPrice: 1448,
    basicUnit: "units",
    presentation: 1,
    category: "Antibiotic",
    quantityOnShelf: 10,
    type: "pay_as_you_sell",
    eligibleForPAYS: true,
    eligibleForPOD: true,
  ),
  Product(
    id: "product:6229",
    fullName: "Lokmal QS Combi",
    unitPrice: 604,
    basicUnit: "units",
    presentation: 1,
    category: "Antimalarial",
    quantityOnShelf: 10,
    type: "pay_as_you_sell",
    eligibleForPAYS: true,
    eligibleForPOD: true,
  ),
  Product(
    id: "product:6005",
    fullName: "Tab Augmentin 625mg",
    unitPrice: 3022,
    basicUnit: "14 tablets",
    presentation: 1,
    category: "Antibiotic",
    quantityOnShelf: 10,
    type: "pay_as_you_sell",
    eligibleForPAYS: true,
    eligibleForPOD: true,
  ),
  Product(
    id: "product:6240",
    fullName: "Zinnat 250mg",
    unitPrice: 2639,
    basicUnit: "units",
    presentation: 1,
    category: "Antibiotic",
    quantityOnShelf: 10,
    type: "pay_as_you_sell",
    eligibleForPAYS: true,
    eligibleForPOD: true,
  ),
];
