// File contains all the paths to the svg icons

const Map<String, String> svgIcons = {
  "intercom": "assets/icons/intercom.svg",
  "home": "assets/icons/home.svg",
  "products": "assets/icons/product.svg",
  "counts": "assets/icons/orderedList.svg",
  "deliveries": "assets/icons/truck.svg",
  "finances": "assets/icons/landmark.svg",
  "lightning": "assets/icons/iconLightning.svg",
  "wave": "assets/icons/iconWave.svg",
  "arrow": "assets/icons/arrow.svg",
  "POD": "assets/icons/iconPod.svg",
  "PAYS": "assets/icons/iconPays.svg",
  "PODLabel": "assets/icons/payOnDelivery.svg",
  "PAYSLabel": "assets/icons/payAsYouSell.svg",
  "fire": "assets/icons/iconFire.svg",
  "plus": "assets/icons/plus.svg",
  "moneyBag": "assets/icons/iconMoneyBag.svg",
  "medal": "assets/icons/iconBest.svg",
  "money": "assets/icons/iconMoney.svg",
  "seasonal": "assets/icons/iconSeason.svg",
  "new": "assets/icons/iconNew.svg",
  "checkMark": "assets/icons/circlecheckmark.svg",
  "close": "assets/icons/close.svg",
};
